export { default as SampleBlogPage } from './SampleBlogPage'
export { default as SampleFillPage } from './SampleFillPage'
export { default as SampleFluidPage } from './SampleFluidPage'
export { default as SampleFullPage } from './SampleFullPage'
export { default as SampleAutoplayPage } from './SampleAutoplayPage'
export { default as SampleAdsPage } from './SampleAdsPage'
export { default as SampleLazyLoadPage } from './SampleLazyLoadPage'
