version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Bangkok

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Bangkok
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
